[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.37"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000_000
via_ir = false
ignored_warnings_from = ["lib"]
fuzz = { runs = 256 }

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.37"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000_000
via_ir = false
ignored_warnings_from = ["lib"]
fuzz = { runs = 512 }
