name: test
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
env:
  FOUNDRY_PROFILE: ci
jobs:
  check:
    name: Foundry build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1.9.1
        with:
          version: v1.8.3
      - run: forge build --sizes
      - run: forge test -vvv
      - run: forge lint -D warnings
